version: "3.8"

services:
  whatsappapi:
    image: whatsappapi:latest
    container_name: whatsappapi
    ports:
      - "8080:5000"
    environment:
      - WUZAPI_ADMIN_TOKEN
      - WUZAPI_GLOBAL_ENCRYPTION_KEY
      - WUZAPI_GLOBAL_HMAC_KEY
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - DB_HOST
      - DB_PORT
      - TZ
    networks:
      - whatsappapi-network
    restart: always

networks:
  whatsappapi-network:
    driver: bridge